name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sqlalchemy
  - pydantic=1.9.*
  - pip
  - pip:
      - hummingbot
      - streamlit
      - watchdog
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - commlib-py
      - jupyter
      - optuna
      - optuna-dashboard
      - pathlib
      - streamlit-ace
      - st-pages
      - streamlit-elements==0.1.*
      - streamlit-authenticator
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - git+https://github.com/hummingbot/docker-manager.git
